exclude:
  - node_modules
  - public
  - dist
  - src
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - handleFiles.js
  - package-lock.json
  - package.json
  - README.md
  - vue.config.js

# Markdown

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true

# Path

collections:
  articles:
    output: true
  notes:
    output: true

# Site info

pathSplite: "-" # a sign to split page url