exclude:
  - build
  - config
  - image
  - src
  - .babelrc
  - .gitignore
  - .postcssrc.js
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - node_modules
  - template.html

# Markdown

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true

# Path

collections:
  articles:
    output: true
  notes:
    output: true

# Site info

pathSplite: "-" # a sign to split page url