exclude:
  - build
  - config
  - image
  - src
  - .babelrc
  - .gitignore
  - .postcssrc.js
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - node_modules
  - template.html

# Markdown

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true

# Path

collections:
  articles:
    output: true
  notes:
    output: true
  demos:
    output: true

# Defaults

defaults:
  - scope:
      path: ""
      type: articles
    values:
      column: Article
  - scope:
      path: ""
      type: notes
    values:
      column: Note

# Site info

url: "" # the base hostname & protocol for your site, e.g. http://example.com
title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog

pathSplite: "-" # a sign to split page url